### ISSUE TITLE
makegdimg doesnt seem to work with nrg images

### ISSUE THREAD

**Issue by BadAd84** [zeldin/iceGDROM#1]
makegdimg doesnt seem to recognise any nrg images I have tried to use. GDI works fine.

There is also a tool called cdi2nrg, which the resulting files do not work either.

**Comment by zeldin** [comment]
Not much to go on here...  It works with all the nrg images I've tried it with obviously.

Could you provide a sample of a file that does not work?  Do you know what sector format it uses?  Do you get any error messages?

**Comment by BadAd84** [comment]
![screenshot 2016-12-20 12 41 39](https://cloud.githubusercontent.com/assets/598804/21351135/e46dda94-c6b2-11e6-9b3c-dfd7d674380c.png)

This is the error message, seems like its just falling through the detection code. 

Also note, while I have compiled it with cygwin for windows, the error is the same under linux too. (and gdi images work on both).

Test image here:
http://www.filedropper.com/image

**Comment by zeldin** [comment]
Thanks.  This seems to be a pre-Nero5 file, using the old footer format.  I didn't implement support for it since I assumed everyone would be using Nero5 or newer.  I'll see if I can add it.

**Comment by BadAd84** [comment]
The above image was created using "cdi2nrg", if you could implement it - it would make things easier if you already have a colllection of CDI's (which as you likely know, was the format used at the time).

Here is another image, but created in nero 2017 which also doesnt work (maybe they updated the format again?).

![screenshot 2016-12-20 13 06 07](https://cloud.githubusercontent.com/assets/598804/21351624/70772fd4-c6b5-11e6-9c12-797dc443378c.png)

http://www.filedropper.com/image2


At which point, I gave up and logged the issue.

**Comment by zeldin** [comment]
Well, it would make more sense to implement DiscJuggler support directly then, which is actually on my to-do-list.  :-)
I'll check the other image too.

**Comment by BadAd84** [comment]
Excellent, thank you.

To avoid making another issue, are you aware of the performance issues? I have tested some images, but load times are much slower, with audio skipping etc.

**Comment by zeldin** [comment]
There is a benchmark program in the git repo that you can try.  I get performance which is similar to physical GD-ROM (and better than CD-R), but it will depend a lot on the speed grade of the SD card.  Seeks can be slow due to the structure of FAT filesystems, but then so are seeks on a physical disk.
I'm planning to do a writeup on performance and the different bottlenecks later.

**Comment by BadAd84** [comment]
When I compile, the test folder has the obj folder created, but nothing is within it.

If you have suggests for fixing that or have the binaries that I can test, I can try a bunch of sd cards.

**Comment by zeldin** [comment]
Use `make tests` to build the test stuff.

As for the Nero2017 file, as the error message says it uses track mode 0x0200, which is not one of those listed on https://en.wikipedia.org/wiki/NRG_(file_format).  Since the sector size is 2048 and the number is close to 0x0300, I'm guessing this is CD-XA mode 2 form 1 without the subheader and ECC data.  I don't suppose you can confirm that?

**Comment by Xerxes3rd** [comment]
zeldin, do you have a link to the SH4 GCC compiler used in 'make tests'?  I couldn't find it as of a few weeks ago when I was playing with iceGDROM.

**Comment by zeldin** [comment]
@Xerxes3rd GCC source code is available from http://gcc.gnu.org/.  Just specify --target=sh-elf when you build it.

**Comment by zeldin** [comment]
@BadAd84 Regarding that first (pre Nero-5) image, there's something wonky about it besides using the old Nero format.  There is only one track (#1) listed in the CUES and DAOI chunks, but yet the SINF chunks indicate that there should be two sessions, with one track in each.  That does not add up...

**Comment by zeldin** [comment]
@BadAd84 I've now pushed two commits which should handle the 0x200 type of Nero2017, and also the older pre-Nero5 format.  As I mentioned, your `image.nrg` is broken, so it's not going to convert anyway.  The CUES and DAOI chunks specify a single track of 7.5 minutes, which equals 75 megabytes of data.  However, the image file is 777 megabytes large, so there is clearly data there for a second longer track, all the metadata for it is just missing.  So it seems like this `cdi2nrg` tool did not do a proper job.
