### ISSUE TITLE
REplacement delisted parts

### ISSUE THREAD

**Issue by jmoleiro** [zeldin/iceGDROM#4]
Hi! On Mouser these parts are delisted

9 pin header - 517-9611096804AR
3 pin header - 517-9611036804AR

Any idea which alternative parts can i use?

Thanks

John

**Comment by zeldin** [comment]
Hi.  For these headers the exact height isn't important, so basically you can pick any header with 2.54 mm pitch and the correct number of pins.

e.g.
855-M20-9770942
855-M20-9770342
should be suitable replacements.
